### PR TITLE
Migrate to Swift 3.0

### PR DESCRIPTION
**Pull request by Nodepad**
Tests pass, except `testUpsert` and `testDel`. They fail on my machine: function `SecItemAdd` inside of `SwKeyStore.upsertKey` method returns status `-34018`. This happens before and after migration.

### CODE REVIEW

**Comment by soyersoyer** [comment]
thanks

**Comment by jariz** [comment]
Can you add a new tag as well?

**Comment by soyersoyer** [comment]
sure :)

**Comment by jariz** [comment]
Much appreciated!

**Comment by maeda-kazuya** [comment]
Thanks!

**Pull request merged**
